version: 0.0
os: linux
files:
  - source: /
    destination: /www
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
#  ApplicationStop:
#    - location: scripts/stop_server
#      timeout: 300
#      runas: root
